### ISSUE TITLE
why calling rev()?

### ISSUE THREAD

**Issue by quamis** [GrayJack/algos#1]
https://github.com/GrayJack/algos/blob/ce8385c6306df5107196b98365001be7149caf94/src/sort.rs#L62

wouldn't reversing the list slow the sorting?

**Comment by GrayJack** [comment]
Not really, if you look at the implementation of `rev()`, it wraps the iterator in `Rev(iter: self)`.
In the `Rev` definition, `next()` is defined as `next_back()`.  Furthermore, `next_back` for `Range<A>` is defined as:

```rust
fn next_back(&mut self) -> Option<A> {
        if self.start < self.end {
            self.end = self.end.sub_one();
            Some(self.end.clone())
        } else {
            None
        }
}
```

From the implementation we can infer that it will directly generate the reverse sequence instead of putting the entire sequence in memory and then reversing. Thus, `rev()` is still lazy if the source iterator is lazy. That means that reversing has the same cost as not reversing it, hence "Zero Cost Abstractions" as rust priorities

**Comment by quamis** [comment]
Makes sense. Thx
